okta:
  oauth2:
    issuer: https://dev-3ej66wywfny83kba.us.auth0.com/
    client-id: 2h6gYui0FOj7Bct2sOF3z9Dk0xJn7zrf
    client-secret: gsd5-XP-c_0J5IqyB3Rzk3KVgN4YXhUNCCvPhIfCNLXWwi5CfgEbHMEp3O2qV6Qi