spring.application.name=gamehub

spring.datasource.url=jdbc:postgresql://localhost:5432/game_hive
spring.datasource.username=cillianquinn
spring.datasource.password=YOUR_POSTGRES_PASSWORD

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true